--------------------------------------------------------
--  DDL for Table ACCESOS
--------------------------------------------------------

  CREATE TABLE "CONDOMINIO"."ACCESOS" 
   (	"ID_ACCESO" NUMBER(10,0), 
	"FECHA" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"ID_VISITANTE" NUMBER(15,0), 
	"FILIAL" NUMBER(10,0), 
	"H_ENTRADA" VARCHAR2(50 BYTE), 
	"H_SALIDA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO" ;
--------------------------------------------------------
--  DDL for Table CUOTAS
--------------------------------------------------------

  CREATE TABLE "CONDOMINIO"."CUOTAS" 
   (	"ID_CUOTA" NUMBER(10,0), 
	"FECHA" VARCHAR2(20 BYTE), 
	"MONTO" NUMBER, 
	"ID_DUENIO" NUMBER(15,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO" ;
--------------------------------------------------------
--  DDL for Table CUOTAS_EXTRAS
--------------------------------------------------------

  CREATE TABLE "CONDOMINIO"."CUOTAS_EXTRAS" 
   (	"ID_CUOTA_EXTRA" NUMBER(10,0), 
	"FECHA" VARCHAR2(20 BYTE), 
	"MONTO" NUMBER(10,0), 
	"ID_DUENIO" NUMBER(15,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO" ;
--------------------------------------------------------
--  DDL for Table DUENIOS
--------------------------------------------------------

  CREATE TABLE "CONDOMINIO"."DUENIOS" 
   (	"ID_DUENIO" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APE1" VARCHAR2(20 BYTE), 
	"APE2" VARCHAR2(20 BYTE), 
	"TELEFONO" NUMBER(8,0), 
	"CORREO" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO" ;
--------------------------------------------------------
--  DDL for Table FILIALES
--------------------------------------------------------

  CREATE TABLE "CONDOMINIO"."FILIALES" 
   (	"ID_FILIAL" NUMBER(10,0), 
	"ID_DUENIO" NUMBER(15,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO" ;

--------------------------------------------------------
--  DDL for Trigger CREAR_CUOTA_IMPUESTOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "CONDOMINIO"."CREAR_CUOTA_IMPUESTOS" 
AFTER INSERT ON CONDOMINIO.CUOTAS
FOR
EACH ROW
    BEGIN
        INSERT INTO CONDOMINIO.CUOTAS_EXTRAS (ID_CUOTA_EXTRA, FECHA, MONTO, ID_DUENIO, DESCRIPCION) 
        VALUES(:NEW.ID_CUOTA, CURRENT_DATE, :NEW.MONTO * 0.13, :NEW.ID_DUENIO, 'IMPUERTO POR CUOTA');
    END;
/
ALTER TRIGGER "CONDOMINIO"."CREAR_CUOTA_IMPUESTOS" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCESOS
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."ACCESOS" MODIFY ("ID_ACCESO" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."ACCESOS" MODIFY ("FILIAL" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."ACCESOS" ADD CONSTRAINT "PK_ACCESOS" PRIMARY KEY ("ID_ACCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUOTAS
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."CUOTAS" MODIFY ("ID_CUOTA" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."CUOTAS" MODIFY ("ID_DUENIO" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."CUOTAS" ADD CONSTRAINT "PK_COUTAS" PRIMARY KEY ("ID_CUOTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUOTAS_EXTRAS
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."CUOTAS_EXTRAS" MODIFY ("ID_CUOTA_EXTRA" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."CUOTAS_EXTRAS" MODIFY ("ID_DUENIO" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."CUOTAS_EXTRAS" ADD CONSTRAINT "PK_COUTAS_EX" PRIMARY KEY ("ID_CUOTA_EXTRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DUENIOS
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."DUENIOS" MODIFY ("ID_DUENIO" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."DUENIOS" ADD CONSTRAINT "PK_DUENIOS" PRIMARY KEY ("ID_DUENIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FILIALES
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."FILIALES" MODIFY ("ID_FILIAL" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."FILIALES" MODIFY ("ID_DUENIO" NOT NULL ENABLE);
  ALTER TABLE "CONDOMINIO"."FILIALES" ADD CONSTRAINT "PK_FILIALES" PRIMARY KEY ("ID_FILIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONDOMINIO"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCESOS
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."ACCESOS" ADD CONSTRAINT "FK_F_ACCESO" FOREIGN KEY ("FILIAL")
	  REFERENCES "CONDOMINIO"."FILIALES" ("ID_FILIAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUOTAS
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."CUOTAS" ADD CONSTRAINT "FK_IDD_CUOTAS" FOREIGN KEY ("ID_DUENIO")
	  REFERENCES "CONDOMINIO"."DUENIOS" ("ID_DUENIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUOTAS_EXTRAS
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."CUOTAS_EXTRAS" ADD CONSTRAINT "FK_IDD_CUOTAS_EX" FOREIGN KEY ("ID_DUENIO")
	  REFERENCES "CONDOMINIO"."DUENIOS" ("ID_DUENIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FILIALES
--------------------------------------------------------

  ALTER TABLE "CONDOMINIO"."FILIALES" ADD CONSTRAINT "FK_F_DUENIO" FOREIGN KEY ("ID_DUENIO")
	  REFERENCES "CONDOMINIO"."DUENIOS" ("ID_DUENIO") ENABLE;


   CREATE SEQUENCE  "CONDOMINIO"."NUM_VISITANTE"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
   
   
   
   
   --------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_ACCESOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_ACTUALIZAR_ACCESOS" (IDACCESOCUR IN NUMBER, HSALIDAN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    UPDATE CONDOMINIO.ACCESOS SET H_SALIDA = HSALIDAN WHERE ID_ACCESO = IDACCESOCUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_ACTUALIZAR_ACCESOS;

/
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_CUOTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_ACTUALIZAR_CUOTA" (IDCUOTACUR IN NUMBER,
FECHAN IN VARCHAR2, MONTON IN NUMBER, DESCRIPCIONN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    UPDATE CONDOMINIO.CUOTAS SET FECHA = FECHAN, MONTO = MONTON, DESCRIPCION = DESCRIPCIONN
    WHERE ID_CUOTA = IDCUOTACUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_ACTUALIZAR_CUOTA;

/
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_CUOTAS_EXTRAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_ACTUALIZAR_CUOTAS_EXTRAS" (CUOTAIDCUR IN NUMBER,
FECHAN IN VARCHAR2, MONTON IN FLOAT, DESCRIPCIONN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    UPDATE CUOTAS_EXTRAS SET FECHA = FECHAN, MONTO = MONTON, DESCRIPCION = DESCRIPCIONN
    WHERE ID_CUOTA_EXTRA = CUOTAIDCUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_ACTUALIZAR_CUOTAS_EXTRAS;

/
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_DUENIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CONDOMINIO"."SP_ACTUALIZAR_DUENIO" (IDDUENIOCUR IN NUMBER, 
NOMBREN IN VARCHAR2, APE1N IN VARCHAR2, APE2N IN VARCHAR2, TELEFONON IN NUMBER,
CORREON IN VARCHAR2)
IS
--VARIABLES
BEGIN
    UPDATE DUENIOS SET NOMBRE = NOMBREN, APE1 = APE1N, 
    APE2 = APE2N, TELEFONO = TELEFONON, CORREO = CORREON
    WHERE ID_DUENIO = IDDUENIOCUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_ACTUALIZAR_DUENIO;

/
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_FILIALES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_ACTUALIZAR_FILIALES" (IDN IN NUMBER,
 ID_DUENON IN NUMBER,DESCRIPCIONN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    UPDATE FILIALES SET DESCRIPCION = DESCRIPCIONN, ID_DUENIO = ID_DUENON
    WHERE ID_FILIAL = IDN;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_ACTUALIZAR_FILIALES;

/
--------------------------------------------------------
--  DDL for Procedure SP_BORRAR_ACCESOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_BORRAR_ACCESOS" (IDACCESOCUR IN NUMBER)
IS
--VARIABLES
BEGIN
    DELETE FROM CONDOMINIO.ACCESOS WHERE ID_ACCESO = IDACCESOCUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_BORRAR_ACCESOS;

/
--------------------------------------------------------
--  DDL for Procedure SP_BORRAR_CUOTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_BORRAR_CUOTA" (IDCUOTACUR IN NUMBER)
IS
--VARIABLES
BEGIN
    DELETE FROM CONDOMINIO.CUOTAS 
    WHERE ID_CUOTA = IDCUOTACUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_BORRAR_CUOTA;

/
--------------------------------------------------------
--  DDL for Procedure SP_BORRAR_CUOTAS_EXTRAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_BORRAR_CUOTAS_EXTRAS" (CUOTAIDCUR IN NUMBER)
IS
--VARIABLES
BEGIN
    DELETE FROM CUOTAS_EXTRAS WHERE ID_CUOTA_EXTRA = CUOTAIDCUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_BORRAR_CUOTAS_EXTRAS;

/
--------------------------------------------------------
--  DDL for Procedure SP_BORRAR_DUENIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE  PROCEDURE "CONDOMINIO"."SP_BORRAR_DUENIO" (IDDUENIOCUR IN NUMBER)
IS
--VARIABLES
BEGIN
    DELETE FROM DUENIOS 
    WHERE ID_DUENIO = IDDUENIOCUR;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_BORRAR_DUENIO;

/
--------------------------------------------------------
--  DDL for Procedure SP_BORRAR_FILIALES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_BORRAR_FILIALES" (IDN IN NUMBER)
IS
--VARIABLES
BEGIN
    DELETE FROM FILIALES 
    WHERE ID_FILIAL = IDN;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_BORRAR_FILIALES;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_ACCESOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_INSERTAR_ACCESOS" (IDACCESON IN NUMBER,
FECHAN IN VARCHAR2, FILIALN IN NUMBER,
HENTRADAN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    INSERT INTO CONDOMINIO.ACCESOS (ID_ACCESO, FECHA, ID_VISITANTE, FILIAL, H_ENTRADA) 
    VALUES(IDACCESON, FECHAN,NUM_VISITANTE.NEXTVAL , FILIALN, HENTRADAN);
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_INSERTAR_ACCESOS; 

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_CUOTAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_INSERTAR_CUOTAS" (IDCUOTAN IN NUMBER,
FECHAN IN VARCHAR2, MONTON IN NUMBER, IDDUENION IN NUMBER, 
 DESCRIPCIONN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    INSERT INTO CONDOMINIO.CUOTAS (ID_CUOTA, FECHA, MONTO, ID_DUENIO, DESCRIPCION) 
    VALUES(IDCUOTAN, FECHAN, MONTON, IDDUENION, DESCRIPCIONN);
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_INSERTAR_CUOTAS;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_CUOTAS_EXTRAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_INSERTAR_CUOTAS_EXTRAS" (CUOTAIDN IN NUMBER,
FECHAN IN VARCHAR2, MONTON IN FLOAT, DUENIOIDN IN NUMBER, 
 DESCRIPCIONN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    INSERT INTO CUOTAS_EXTRAS (ID_CUOTA_EXTRA,FECHA, MONTO, ID_DUENIO,  DESCRIPCION) 
    VALUES(CUOTAIDN, FECHAN, MONTON, DUENIOIDN, DESCRIPCIONN);
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_INSERTAR_CUOTAS_EXTRAS; 

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_DUENIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE  PROCEDURE "CONDOMINIO"."SP_INSERTAR_DUENIOS" (IDDUENION IN NUMBER, 
NOMBREN IN VARCHAR2, APE1N IN VARCHAR2, APE2N IN VARCHAR2, TELEFONON IN NUMBER,
CORREON IN VARCHAR2)
IS
--VARIABLES
BEGIN
    INSERT INTO DUENIOS (ID_DUENIO, NOMBRE, APE1, APE2, TELEFONO, CORREO) 
    VALUES(IDDUENION, NOMBREN, APE1N, APE2N, TELEFONON, CORREON);
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_INSERTAR_DUENIOS;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_FILIALES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_INSERTAR_FILIALES" (IDN IN NUMBER,
 ID_DUENON IN NUMBER,DESCRIPCIONN IN VARCHAR2)
IS
--VARIABLES
BEGIN
    INSERT INTO FILIALES (ID_FILIAL, ID_DUENIO, DESCRIPCION) 
    VALUES(IDN,ID_DUENON, DESCRIPCIONN );
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_INSERTAR_FILIALES; 

/
----------------------------------------------------
--  DDL for Procedure SP_MOSTRAR_DATOS_PAGOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "CONDOMINIO"."SP_MOSTRAR_DATOS_PAGOS" 
(ID IN NUMBER,  p_cursor OUT NOCOPY SYS_REFCURSOR )
as begin
  open p_cursor for 
    SELECT FILIALES.DESCRIPCION, DUENIOS.NOMBRE, CUOTAS.MONTO,  CUOTAS.FECHA
        FROM DUENIOS
        JOIN FILIALES ON FILIALES.ID_DUENIO = DUENIOS.ID_DUENIO
        JOIN CUOTAS ON CUOTAS.ID_DUENIO = DUENIOS.ID_DUENIO
        WHERE DUENIOS.ID_DUENIO = ID;

end;

/

----------------------------------------------------
--  CURSOR
--------------------------------------------------------

SET SERVEROUTPUT ON;
declare
    v_cursor SYS_REFCURSOR;
    DESCRIPCION VARCHAR2(50 BYTE);
    NOMBRE VARCHAR2(20 BYTE);
    MONTO NUMBER;
    FECHA VARCHAR2(50 BYTE);
begin
  SP_MOSTRAR_DATOS_PAGOS(26412	, v_cursor );
  loop
    fetch v_cursor into DESCRIPCION, NOMBRE, MONTO,FECHA;
    exit when v_cursor%NOTFOUND;
    dbms_output.put_line(DESCRIPCION || ' | ' || NOMBRE
      || ' | ' || MONTO || ' | ' || FECHA);
  end loop;
  close v_cursor;
end;

